export const shopData = [
  {
    id: 1,
    name: 'Kitagwa Marine Figurine',
    price: 750,
    rate: ' ★★★★☆',
    description: 'The Kitagawa Marine Figurine is a highly detailed collectible figure based on the popular character from the anime series "Dress Up Darling" This figurine captures Kitagawa Marine in her iconic school outfit. Standing at approximately 7 inches tall, the figure is made from high-quality PVC material, ensuring durability and a premium feel. It is a must-have for fans of the series and collectors of anime merchandise.',
    image: require('../assets/images/kitagawa.webp'),
  },
  {
    id: 2,
    name: 'XP-Pen Artist 15.6 Pro Drawing Monitor',
    price: 15000,
    rate: ' ★★★★☆',
    description: 'The XP-Pen Artist 15.6 Pro is a high-quality drawing monitor designed for digital artists and designers. It features a 15.6-inch Full HD display with vibrant colors and a responsive pen that offers 8192 levels of pressure sensitivity, allowing for precise and natural drawing experiences. The monitor is compatible with various operating systems and creative software, making it a versatile tool for professionals and hobbyists alike.',
    image: require('../assets/images/XpPenArtistPro15.6.avif'),
  },
  {
    id: 3,
    name: 'Lenovo Legion Pro 7i Gaming Laptop',
    price: 120000,
    rate: ' ★★★★★',
    description: 'The Lenovo Legion Pro 7i is a high-performance gaming laptop designed for gamers and power users. It features a sleek design with a robust build quality, equipped with the latest Intel processors and NVIDIA graphics cards to deliver exceptional gaming performance. The laptop boasts a high-refresh-rate display, advanced cooling technology, and customizable RGB lighting, making it an ideal choice for immersive gaming experiences and demanding tasks.',
    image: require('../assets/images/lenovo-legion-pro-7i-gaming-laptop.jpg'),
  },
  {
    id: 4,
    name: 'Relax Time Ookami Mio Figurine',
    price: 750,
    rate: ' ★★★★☆',
    description: 'The Relax Time Ookami Mio Figurine is a beautifully crafted collectible figure based on the character Ookami Mio from the popular virtual YouTuber group Hololive. This figurine captures Mio in a relaxed pose, showcasing her charming personality and signature wolf ears. Made from high-quality materials, the figure features intricate details and vibrant colors, making it a must-have for fans of Hololive and collectors of anime merchandise.',
    image: require('../assets/images/relaxtimeookamiMio.jpg'),
  },
  {
    id: 5,
    name: 'Yugioh Card 25th Collection',
    price: 2000,
    rate: ' ★★★★☆',
    description: 'The Yugioh Card 25th Collection is a special edition set featuring exclusive cards from the 25th anniversary of the Yu-Gi-Oh! trading card game. This collection includes rare and limited edition cards that are highly sought after by collectors and fans of the franchise.',
    image: require('../assets/images/yugioh 25.webp'),
  },
  {
    id: 6,
    name: 'Playstation 5 Gaming Console',
    price: 45000,
    rate: ' ★★★★☆',
    description: 'The PlayStation 5 is a next-generation gaming console developed by Sony Interactive Entertainment. It features a custom AMD Zen 2 CPU and RDNA 2 GPU, offering enhanced performance and visual quality. The console supports 4K gaming at up to 120 frames per second, includes haptic feedback and adaptive triggers in the DualSense controller, and offers fast loading times thanks to its ultra-high-speed SSD.',
    image: require('../assets/images/Gaming-Console-Playstation-5.webp'),
  },
];
